name: huxt

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - astropy=4.2
  - h5py==3.1.0
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - jupyterlab=3.0.10
  - matplotlib=3.3.4
  - numpy=1.20.1
  - numba=0.53.0
  - pip=21.0.1
  - scipy=1.6.0
  - sunpy=2.1.2
  - moviepy==1.0.1
  - httplib2==0.19.0
  - pyhdf==0.10.2
